[package]
name = "discord-bot"
version = "0.1.0"
authors = ["Jokler <jokler.contact@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = "0.9.3"
log = "0.4.27"
xml-rs = "0.8.26"
reqwest = "0.11.27"
url = "2.5.4"
rand = "0.8.5"
bincode = "1.3.3"
circular-queue = "0.2.7"
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
serenity = { version = "0.12", features = ["voice"] }
poise = "0.6.1"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
